//created on: 18 mag 2022
package com.sample.rules

//list any import classes here.

import com.sample.Sala;
import java.util.ArrayList;

import com.sample.Player;

import com.sample.Owner;
import com.sample.Machine;


//declare any global variables here



/**
* When a boss fails it will be changed.
*/
rule "Boss lose all reputation"
	agenda-group "bossOwn"
    when
        $s: Sala (getBoss().isFailed())
    then
    	$s.changeBoss();
    	System.out.println("The old boss is failed, Now boss is welcome!");
        //actions

end

rule "Boss with good reputation"
	agenda-group "bossOwn"
    when
        Sala(getBoss().getReputation() >=25.0) 
    then 
    	System.out.println("Boss with good reputation!");
        //actions

end


query "Boss don't fail for a lot of round" ($own) 
	Player( humor==false )
end
